In [ ]:
import pandas as pd
import numpy as np


In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/My Drive/100-days-of-machine-learning/day28-column-transformer/covid_toy.csv')

In [ ]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df["city"].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [ ]:
df["cough"].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [ ]:
df["gender"].value_counts()

Female    59
Male      41
Name: gender, dtype: int64

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)
# df.drop(columns=["has_covid"])---------include all columns except has_covid column

In [ ]:
x_train

age  gender  fever   cough       city
57   49  Female   99.0  Strong  Bangalore
61   81  Female   98.0  Strong     Mumbai
22   71  Female   98.0  Strong    Kolkata
69   73  Female  103.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
48   66    Male   99.0  Strong  Bangalore
45   72    Male   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
96   51  Female  101.0  Strong    Kolkata
26   19  Female  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [ ]:
x_test

age  gender  fever   cough       city
14   51    Male  104.0    Mild  Bangalore
65   69  Female  102.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
86   25    Male  104.0    Mild  Bangalore
93   27    Male  100.0    Mild    Kolkata
84   69  Female   98.0  Strong     Mumbai
75    5    Male  102.0    Mild    Kolkata
77    8  Female  101.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
95   12  Female  104.0    Mild  Bangalore
16   69  Female  103.0    Mild    Kolkata
5    84  Female    NaN    Mild  Bangalore
38   49  Female  101.0    Mild      Delhi
94   79    Male    NaN  Strong    Kolkata
56   71    Male    NaN  Strong    Kolkata
88    5  Female  100.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai
63   10    Male  100.0    Mild  Bangalore

In [ ]:
y_train

57     No
61     No
22    Yes
69     No
73    Yes
     ... 
48     No
45     No
62    Yes
96    Yes
26    Yes
Name: has_covid, Length: 80, dtype: object

In [ ]:
y_test

14     No
65     No
36     No
99    Yes
97     No
86    Yes
93    Yes
84     No
75    Yes
77     No
49     No
95     No
16    Yes
5     Yes
38    Yes
94    Yes
56     No
88     No
54    Yes
63     No
Name: has_covid, dtype: object

In [ ]:
# adding simple imputer to fever column
si=SimpleImputer()
x_train_fever = si.fit_transform(x_train[["fever"]])
# missing values are being replaced by mean here above

In [ ]:
x_test_fever = si.fit_transform(x_test[["fever"]])


In [ ]:
x_test_fever

array([[104.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [103.        ],
       [101.29411765],
       [101.        ],
       [101.29411765],
       [101.29411765],
       [100.        ],
       [ 99.        ],
       [100.        ]])

In [ ]:
x_train_fever.shape

(80, 1)

In [ ]:
# OrdinalEncoding -->cough

In [ ]:
oe = OrdinalEncoder(categories = [["Mild","Strong"]])
x_train_cough = oe.fit_transform(x_train[["cough"]])

# also for test data
x_test_cough = oe.fit_transform(x_test[["cough"]])

# x_train_cough
x_train_cough.shape

(80, 1)

In [ ]:
# OneHotCoding -> gender , city
ohe = OneHotEncoder(drop = "first", sparse = False)

x_train_gender_city = ohe.fit_transform(x_train[["gender","city"]])

# also the test data

x_test_gender_city = ohe.fit_transform(x_test[["gender","city"]])

x_train_gender_city
# x_train_gender_city.shape

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],


In [ ]:
# Extracting Age
x_train_age = x_train.drop(columns=["gender","fever","cough","city"]).values

# also for the test data

x_test_age = x_test.drop(columns=["gender","fever","cough","city"]).values
x_train_age

array([[49],
       [81],
       [71],
       [73],
       [34],
       [73],
       [23],
       [24],
       [ 6],
       [74],
       [11],
       [47],
       [26],
       [70],
       [64],
       [55],
       [16],
       [38],
       [51],
       [20],
       [80],
       [34],
       [22],
       [27],
       [11],
       [59],
       [34],
       [15],
       [65],
       [13],
       [42],
       [49],
       [19],
       [34],
       [ 5],
       [82],
       [82],
       [46],
       [23],
       [65],
       [65],
       [27],
       [54],
       [19],
       [14],
       [19],
       [25],
       [20],
       [68],
       [47],
       [64],
       [50],
       [40],
       [17],
       [83],
       [33],
       [12],
       [31],
       [42],
       [82],
       [14],
       [83],
       [24],
       [48],
       [18],
       [64],
       [65],
       [83],
       [80],
       [42],
       [75],
       [16],
       [81],
       [60],
       [75],
       [66],
       [72],

In [ ]:
x_train_age.shape

(80, 1)

In [ ]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [ ]:
# x_train_transformed
x_train_transformed.shape

(80, 7)

In [ ]:
# ColumnTransformer
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers = [
    ('tnf1',SimpleImputer(),["fever"]),
    ('tnf2',OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ('tnf3',OneHotEncoder(sparse=False,drop="first"),["gender","city"]),
],remainder="passthrough")

In [ ]:
transformer.fit_transform(x_train)

array([[ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [100.73972603,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.    

In [ ]:
transformer.fit_transform(x_train).shape

(80, 7)

In [ ]:
transformer.fit_transform(x_test).shape

(20, 7)