In [ ]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
# 100 rows
# 2 input clos
# 1 output col
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [ ]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [ ]:
X

array([[ 7.80156089e-01, -1.04515803e+00],
       [ 6.30774593e-01, -2.37635705e-01],
       [-1.14690875e+00,  1.24147668e+00],
       [ 7.86793157e-01, -1.06846008e+00],
       [-1.17184935e+00, -8.88502089e-03],
       [ 7.66998010e-01,  5.71302213e-01],
       [-3.51964200e-01,  1.18030271e+00],
       [ 2.03045465e+00, -3.20075292e-01],
       [-4.65760971e-01,  2.07625898e-01],
       [-1.67742096e+00, -4.41362144e-01],
       [ 2.78072121e+00, -1.56395153e+00],
       [-1.52416376e-01, -2.08505057e-01],
       [ 2.45134078e-01,  3.58659327e-02],
       [ 5.14170828e-01, -6.31293723e-01],
       [ 1.46247753e-02,  2.78010098e+00],
       [-7.27984585e-01,  5.21661886e-01],
       [ 1.42216715e+00, -8.89785051e-01],
       [ 7.68098490e-02, -1.61484710e+00],
       [ 4.82056908e-01,  1.42409992e+00],
       [-1.86089862e+00,  1.33392831e+00],
       [-7.83253094e-01,  5.57259812e-01],
       [-2.05274552e-01, -4.85802251e-01],
       [ 2.61100260e-02, -2.75887518e-01],
       [ 1.

In [ ]:
y


array([  83.22778416,   24.92733944, -118.59378939,   61.51080809,
        -80.41335776,   13.35710477,   33.87030602,  162.48547887,
          3.72561516, -139.73423541,  102.74243794,  -29.30745509,
         40.9110036 ,   76.32887471,   31.33456654,  -40.20798929,
         62.66072736,  -34.45258073,   90.54931658,  -77.1972452 ,
        -22.2468038 ,  -51.16300283,   34.43966555,  137.74867781,
        108.57415806,  -43.56593246,   50.41061132,  -26.95698893,
        -67.79072509,    9.33872838,  -42.56499438,  -27.57361883,
         43.82551129, -103.18927307,   73.03006878,    4.63328301,
         23.97804123,  142.20932433,  -81.90282931,   32.2504064 ,
        -99.5862061 ,  -51.85539774,   -2.19712828,   71.50715242,
         40.08654974,   15.8687409 ,   32.39895771,   70.2534984 ,
         46.5541468 ,   72.67968489, -106.32622448,    8.65654748,
         62.60289179,   16.53715408,   93.47843009,  -21.835538  ,
        106.24394742,    6.59859471,  -54.47986526,    4.88968

In [ ]:
df.shape

(100, 3)

In [ ]:
df.head()

feature1  feature2      target
0  0.780156 -1.045158   83.227784
1  0.630775 -0.237636   24.927339
2 -1.146909  1.241477 -118.593789
3  0.786793 -1.068460   61.510808
4 -1.171849 -0.008885  -80.413358

In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 38.30976656702339
MSE 2234.6077711061166
R2 score 0.47842747659870055


In [ ]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

z = z_final



In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [ ]:
lr.coef_

array([48.63403268, 17.41945411])

In [ ]:
lr.intercept_

7.188198748730127